language: java

branches:
  only:
    - master
    - /v\d+\.\d+[a-z]/
env:
  global:
    - DOCKER_USER=iosid
    - DOCKER_PASS=dldytjq89!

deploy:
  provider: script
  script: bash docker-deploy.sh
  skip_cleanup: true
  on:
    repo: Yoseob/docker_rest
    tags: true
    all_branches: true